# Builds the final item icon atlases, the generated Luau index and the preview sheets.
#   python3 build_final.py <outdir>
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from PIL import Image, ImageDraw
import equip, others
from render import render, compose, CELL
from preview import sheet, FONT_B, BG
from tiers import TIERS

OUT = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else "out_final")
os.makedirs(OUT, exist_ok=True)
icons = equip.icons() + others.icons()
keys = [i.key for i in icons]
assert len(keys) == len(set(keys)), "duplicate icon key"
index, n = render(icons, OUT, "items")
sheets = {i + 1: Image.open(os.path.join(OUT, f"items_{i + 1}.png")).convert("RGBA") for i in range(n)}
json.dump({"sheets": n, "icons": index, "tiers": {t: c for t, c, _ in TIERS}}, open(os.path.join(OUT, "index.json"), "w"), indent=1)

# ---------------------------------------------------------------- generated Luau index
T = {"m": "tier", "a": "accent", "b": None}
lines = [
    "--!strict",
    "-- GENERATED by tools/icons/build_final.py. Do not edit by hand: change the generator and rebuild.",
    "-- Item icon atlases (art/icons/items_<n>.png, 1024x1024, 128 px cells). An icon is 1-3 stacked layers,",
    "-- drawn in list order:",
    '--   t = "tier"   greyscale material, ImageColor3 = TIER_TINT[def.tier]',
    '--   t = "accent" greyscale accent, ImageColor3 = accent colour (element, potion, ore, scroll seal, ...)',
    "--   t = nil      fixed colours, ImageColor3 = white",
    "-- Sheet asset ids live in Data/ItemIconSheets.luau (filled in by hand after upload).",
    "",
    "export type Layer = { s: number, x: number, y: number, t: (\"tier\" | \"accent\")? }",
    "export type Icon = { accent: string?, layers: { Layer } }",
    "",
    "local TIER_TINT: { [number]: string } = {",
]
for t, c, name in TIERS:
    lines.append(f'\t[{t}] = "{c.upper()}", -- {name}')
lines += ["}", "", "local ICONS: { [string]: Icon } = {"]
for ic in icons:
    e = index[ic.key]
    parts = []
    for L in e["layers"]:
        t = T[L["layer"]]
        parts.append(f'{{ s = {L["sheet"]}, x = {L["x"]}, y = {L["y"]}' + (f', t = "{t}"' if t else "") + " }")
    acc = f'accent = "{e["accent"].upper()}", ' if e["accent"] else ""
    lines.append(f'\t["{ic.key}"] = {{ {acc}layers = {{ {", ".join(parts)} }} }},')
lines += ["}", "", "return table.freeze({", f"\tCELL = {CELL},", f"\tSHEETS = {n},", "\tTIER_TINT = table.freeze(TIER_TINT),",
          "\tICONS = ICONS,", "})", ""]
open(os.path.join(OUT, "ItemIconAtlas.luau"), "w").write("\n".join(lines))

# ---------------------------------------------------------------- previews
PL = {
    "sword1h": "Miecz", "axe1h": "Topór", "mace1h": "Buława", "saber1h": "Szabla", "sword2h": "Miecz 2r",
    "axe2h": "Topór Bojowy", "hammer2h": "Młot Wojenny", "spear2h": "Włócznia", "shortbow": "Łuk Krótki", "bow": "Łuk",
    "longbow": "Łuk Długi", "crossbow": "Kusza", "heavycrossbow": "Ciężka Kusza", "wand": "Różdżka", "staff": "Kostur",
    "runestaff": "Kostur Runiczny", "scepter": "Berło", "flail1h": "Cep", "holystaff": "Kostur Święty", "shield": "Tarcza",
    "quiver": "Kołczan", "tome": "Księga", "orb": "Kula", "relic": "Relikwia", "necklace": "Naszyjnik", "ring": "Pierścień",
    "talisman": "Talizman", "helmet_heavy": "Hełm", "armor_heavy": "Zbroja Płytowa", "gloves_heavy": "Rękawice Płyt.",
    "boots_heavy": "Buty Płytowe", "helmet_medium": "Kaptur", "armor_medium": "Kurta", "gloves_medium": "Karwasze",
    "boots_medium": "Trzewiki", "helmet_light": "Diadem", "armor_light": "Szata", "gloves_light": "Mitenki",
    "boots_light": "Sandały",
    "unique_grimrok_cleaver": "Rozłupywacz", "unique_grimrok_fang": "Kieł Wodza", "unique_grimrok_totem": "Totem Plemienia",
    "unique_morvane_shroud": "Całun Królowej", "unique_morvane_scepter": "Berło Krypt", "unique_morvane_bow": "Łuk Cieni",
    "unique_azgor_heart": "Płomienne Serce", "unique_azgor_staff": "Kostur Pożogi", "unique_azgor_helm": "Hełm Płomieni",
    "unique_vaelgrath_fang": "Kieł Vaelgratha", "unique_vaelgrath_scale": "Łuska Smoka", "unique_vaelgrath_eye": "Oko Zimy",
    "essence_dust": "Pył Esencji", "essence_shard": "Odłamek Esencji", "essence_crystal": "Kryształ Esencji",
    "legend_core": "Rdzeń Legendy", "ore": "Ruda", "herb": "Zioło", "fish": "Ryba", "wolf_pelt": "Wilcza Skóra",
    "boar_tusk": "Kieł Dzika", "spider_silk": "Pajęczy Jedwab", "goblin_ear": "Ucho Goblina", "werewolf_claw": "Pazur Wilkołaka",
    "ectoplasm": "Ektoplazma", "salamander_scale": "Łuska Salamandry", "magma_shard": "Odłamek Magmy", "yeti_fur": "Futro Yeti",
    "frost_scale": "Mroźna Łuska", "thick_hide": "Gruba Skóra", "venom_sac": "Gruczoł Jadu", "feather": "Pióro",
    "cursed_bone": "Przeklęta Kość", "1": "Mikstura I", "2": "Mikstura II", "3": "Mikstura III", "4": "Mikstura IV",
    "5": "Mikstura V", "warrior": "Bł. Wojownika", "hunter": "Bł. Łowcy", "sage": "Bł. Mędrca", "guardian": "Bł. Strażnika",
    "fortune": "Bł. Fortuny", "elixir": "Eliksir", "stone": "Kamień", "scroll": "Zwój", "pickaxe": "Kilof",
    "fishing_rod": "Wędka", "backpack": "Plecak", "gold": "Złoto", "exp": "Doświadczenie", "dragon": "Smocza Waluta",
}
IRON = dict((t, c) for t, c, _ in TIERS)[10]
GREY, YEL, BLUE, ORA, RED = "#9DA3AB", "#F2D33A", "#3D8BFF", "#FF9F1C", "#E5302A"


def label(key):
    return PL.get(key.split("/")[1], key.split("/")[1])


def stack(parts, path):
    W = max(p.width for p in parts)
    H = sum(p.height for p in parts)
    img = Image.new("RGB", (W, H), BG)
    y = 0
    for p in parts:
        img.paste(p, (0, y))
        y += p.height
    img.save(path)


eq = [i for i in icons if i.key.startswith("eq/")]
uq = [i for i in icons if i.key.startswith("uniq/")]
rest = [i for i in icons if not i.key.startswith(("eq/", "uniq/"))]
stack([
    sheet(index, sheets, [(i.key, label(i.key), IRON, i.accent, GREY) for i in eq], "Ekwipunek: 39 typów (tu w progu Żelazny, ramka Zwykły)", cols=10),
    sheet(index, sheets, [(i.key, label(i.key), None, None, RED) for i in uq], "Mityki z bossów: własne ikony (ramka Mityczny)", cols=10),
    sheet(index, sheets, [(i.key, label(i.key), IRON, i.accent, GREY) for i in rest], "Materiały, mikstury, błogosławieństwa, zwoje, narzędzia, waluty", cols=10),
], os.path.join(OUT, "katalog.png"))

rows = []
for k in ("eq/sword1h", "eq/axe2h", "eq/bow", "eq/staff", "eq/shield", "eq/helmet_heavy", "eq/armor_light", "eq/ring"):
    for t, c, name in TIERS:
        rows.append((k, f"{t}", c, index[k]["accent"], GREY))
stack([sheet(index, sheets, rows, "Progi 1-100: kolor materiału (" + ", ".join(f"{t} {n}" for t, _, n in TIERS[:6]) + " ...)", cols=21, slot=80, label_h=22)],
      os.path.join(OUT, "progi.png"))

v = []
for name, frame in (("Zwykły", GREY), ("Unikatowy", YEL), ("Heroiczny", BLUE), ("Legendarny", ORA), ("Mityczny", RED)):
    v.append(("eq/sword1h", name, dict((t, c) for t, c, _ in TIERS)[20], None, frame))
for name, frame in (("Zwykły", GREY), ("Unikatowy", YEL), ("Heroiczny", BLUE), ("Legendarny", ORA), ("Mityczny", RED)):
    v.append(("eq/armor_heavy", name, dict((t, c) for t, c, _ in TIERS)[20], None, frame))
pots = [("pot/%d" % s, f"HP {s}", None, "#C2352E", GREY) for s in range(1, 6)] + \
       [("pot/%d" % s, f"Mana {s}", None, "#3D6FD6", GREY) for s in range(1, 6)] + \
       [("pot/%d" % s, f"Energia {s}", None, "#D9B23A", GREY) for s in range(1, 6)] + \
       [("pot/elixir", n, None, c, GREY) for n, c in (("Ogień", "#FF7A1A"), ("Lód", "#9FE0FF"), ("Błysk.", "#F2E85A"), ("Trucizna", "#7ACB3A"))]
mats = [("mat/ore", n, None, c, GREY) for n, c in (("Miedź", "#B87333"), ("Żelazo", "#8E8E93"), ("Srebro", "#D8D8E0"), ("Mithril", "#7FD4E8"), ("Adamantyt", "#5A3F7A"))] + \
       [("mat/herb", n, None, c, GREY) for n, c in (("Wiązówka", "#E8E4B0"), ("Psianka", "#6B4A9A"), ("Ogniokwiat", "#FF7A1A"), ("Księżycówka", "#E8E8FF"), ("Mroźnik", "#9FE0FF"))] + \
       [("mat/fish", n, None, c, GREY) for n, c in (("Karp", "#B89B5A"), ("Szczupak", "#6F8F5A"), ("Węgorz", "#4A5A3A"), ("Złotopłetw", "#E8C25A"), ("Magmowa", "#D6542A"), ("Lodowa", "#9FD0F0"))]
misc = [("misc/stone", n, None, c, GREY) for n, c in (("Powrotu", "#4A8FE7"), ("Mapy", "#B455FF"), ("Lochu", "#D64A3E"))] + \
       [("misc/scroll", n, None, c, GREY) for n, c in (("Ochrony", "#4FD16B"), ("Zapomnienia", "#C9A45C"), ("Reset", "#4A8FE7"), ("Odwiązania", "#E8C25A"))] + \
       [("misc/backpack", str(n), None, c, GREY) for n, c in ((20, "#B89B5A"), (30, "#9C8A72"), (45, "#8A6B4A"), (60, "#6F8F5A"), (80, "#4A8FE7"), (100, "#3D6FD6"), (130, "#B455FF"), (160, "#FF9F1C"), (200, "#E8C25A"))]
mage = [(k, f"{dict(wand='Różdżka', staff='Kostur', runestaff='Runiczny')[k[3:]]} {e}", IRON, c, GREY) for k in ("eq/wand", "eq/staff", "eq/runestaff") for e, c in (("ogień", "#FF7A1A"), ("lód", "#9FE0FF"), ("błysk.", "#F2E85A"))]
stack([
    sheet(index, sheets, v, "Ramki rzadkości (Stalowy Miecz i Zbroja)", cols=10),
    sheet(index, sheets, mage, "Broń maga: kolor żywiołu", cols=10),
    sheet(index, sheets, pots, "Mikstury i eliksiry: jeden kształt na rozmiar, kolor z danych", cols=10),
    sheet(index, sheets, mats, "Rudy, zioła, ryby: kolor z danych", cols=10),
    sheet(index, sheets, misc, "Kamienie, zwoje, plecaki", cols=10),
], os.path.join(OUT, "warianty.png"))
print("icons", len(icons), "sheets", n, "cells", sum(len(e["layers"]) for e in index.values()))
