// Web fonts (S44), run before every build and dev server: copies the Latin and Latin Extended WOFF2 files of the
// @fontsource packages to public/fonts/ and writes public/fonts/fonts.css (with unicode-range, font-display: swap).
// Base.astro loads that stylesheet without blocking the first paint; until the fonts arrive the text uses the
// size-matched local fallbacks of tokens.css, so the swap does not move the layout. Output is not committed.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const FONTS = [
  ["grenze-gotisch", ["500", "700"]],
  ["alegreya-sans", ["400", "400-italic", "500", "700", "800"]],
  ["ibm-plex-mono", ["400", "500"]],
];
const SUBSETS = /^\/\* [a-z-]+-(latin|latin-ext)-\d+-(normal|italic) \*\/$/;
const OUT = join("public", "fonts");
mkdirSync(OUT, { recursive: true });

const out = ["/* GENERATED by scripts/fonts.mjs from @fontsource (Latin + Latin Extended). */"];
let files = 0;
for (const [pkg, weights] of FONTS) {
  const dir = join("node_modules", "@fontsource", pkg);
  for (const w of weights) {
    const css = readFileSync(join(dir, `${w}.css`), "utf8");
    // blocks: "/* <name> */\n@font-face { ... }"
    for (const m of css.matchAll(/(\/\* [^*]+ \*\/)\s*(@font-face\s*\{[^}]*\})/g)) {
      if (!SUBSETS.test(m[1])) continue;
      const woff2 = /url\(\.\/files\/([^)]+\.woff2)\)/.exec(m[2])?.[1];
      if (!woff2) continue;
      copyFileSync(join(dir, "files", woff2), join(OUT, woff2));
      files++;
      out.push(m[1], m[2].replace(/src:[^;]+;/, `src: url(/fonts/${woff2}) format('woff2');`));
    }
  }
}
writeFileSync(join(OUT, "fonts.css"), `${out.join("\n")}\n`);
console.log(`fonts: ${files} files in public/fonts`);
