// npm run routes (S44): one route file per section and language, src/pages/<lang>/<segment>/[...path].astro, each
// importing only its own view (src/views/paths.ts names it), so a page loads the CSS of its view and not of all of
// them (one catch-all route bundled every view's styles into every page). Reads src/views/paths.ts,
// src/i18n/routes.ts and src/lib/sections.ts as text. `--check` exits 1 when the files are out of date.
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";

const PAGES_DIR = join("src", "pages");
const LANGS = ["pl", "en"];
const check = process.argv.includes("--check");

const paths = readFileSync("src/views/paths.ts", "utf8");
const routes = readFileSync("src/i18n/routes.ts", "utf8");
const sections = readFileSync("src/lib/sections.ts", "utf8");

const entries = [...paths.matchAll(/\{\s*key:\s*"([^"]+)",\s*view:\s*"([^"]+)"/g)].map((m) => ({ key: m[1], view: m[2] }));
const segments = Object.fromEntries([...routes.matchAll(/^\s+(\w+):\s*\{\s*pl:\s*"([^"]*)",\s*en:\s*"([^"]*)"\s*\}/gm)].map((m) => [m[1], { pl: m[2], en: m[3] }]));
const notReady = [...sections.matchAll(/\{\s*id:\s*"([^"]+)",\s*ready:\s*false/g)].map((m) => m[1]);
for (const key of notReady) if (!entries.some((e) => e.key === key)) entries.push({ key, view: "ComingSoon" });

const files = new Map();
for (const { key, view } of entries) {
  for (const lang of LANGS) {
    const segment = key === "404" ? "404" : segments[key]?.[lang];
    if (segment === undefined || segment === "") throw new Error(`routes: no segment for ${key}`);
    const file = join(PAGES_DIR, lang, ...segment.split("/"), "[...path].astro");
    const up = relative(dirname(file), "src").split(sep).join("/");
    files.set(
      file,
      `---
// GENERATED by scripts/routes.mjs (npm run routes): the ${key} pages in ${lang === "pl" ? "Polish" : "English"}, only the ${view} view.
import { pageFor, pagesOf } from "${up}/views/paths";
import View from "${up}/views/${view}.astro";

// A function declaration: the compiler hoisted \`export const getStaticPaths = (...) satisfies ...\` together with the
// next statement, which then ran once at module level.
export function getStaticPaths() {
  return pagesOf("${key}", "${lang}");
}

// 404 routes are rendered without the props of getStaticPaths: the page is then looked up by its address.
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- each view declares its own props
const extra: any = (Astro.props.ids ? Astro.props : pageFor("${key}", "${lang}", Astro.url.pathname.slice("/${lang}/${segment}/".length))).extra;
---
<View lang="${lang}" {...extra}${view === "ComingSoon" ? ` section="${key}"` : ""} />
`,
    );
  }
}

// Existing generated files (to remove stale ones)
function walk(dir, out = []) {
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (name === "[...path].astro" && readFileSync(p, "utf8").includes("GENERATED by scripts/routes.mjs")) out.push(p);
  }
  return out;
}
const existing = LANGS.flatMap((l) => walk(join(PAGES_DIR, l)));
const stale = existing.filter((f) => !files.has(f));
const changed = [...files].filter(([f, text]) => !existsSync(f) || readFileSync(f, "utf8") !== text).map(([f]) => f);

if (check) {
  if (stale.length || changed.length) {
    console.error(`routes: out of date (${[...changed, ...stale].join(", ")}); run npm run routes`);
    process.exit(1);
  }
  console.log(`routes: ${files.size} route files up to date`);
  process.exit(0);
}
for (const f of stale) rmSync(f);
for (const f of changed) {
  mkdirSync(dirname(f), { recursive: true });
  writeFileSync(f, files.get(f));
}
console.log(`routes: ${files.size} route files (${changed.length} written, ${stale.length} removed)`);
