"""Writes the Luau data module (src/shared/Data/Town/city.luau) and the terrain test vectors
(tests/fixtures/cityHeights.luau) from plan.py + extras.py. Run from docs/miasto/tools:
    python3 export.py            (writes into the repository)
    python3 export.py out/city.luau out/cityHeights.luau
Then run `stylua src tests` and `lune run tests/run.luau` in the repository root."""
import math, sys, json
import plan as P
import extras as E


def num(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    r = round(v, 2)
    if r == int(r):
        return str(int(r))
    return repr(r)


def lua(v, ind=0):
    """Compact Luau literal. Dicts keep insertion order; keys are identifiers."""
    if v is None:
        return "nil"
    if isinstance(v, (bool, int, float)):
        return num(v)
    if isinstance(v, str):
        return json.dumps(v, ensure_ascii=False)
    if isinstance(v, (list, tuple)):
        return "{ " + ", ".join(lua(x) for x in v) + " }" if v else "{}"
    if isinstance(v, dict):
        items = [f"{k} = {lua(x)}" for k, x in v.items() if x is not None and not k.startswith("_")]
        return "{ " + ", ".join(items) + " }"
    raise TypeError(type(v))


def pts2(pts):
    return [[round(x, 1), round(z, 1)] for x, z in pts]


def block(name, rows, comment=None):
    out = []
    if comment:
        out.append(f"\t-- {comment}")
    out.append(f"\t{name} = {{")
    for r in rows:
        out.append(f"\t\t{lua(r)},")
    out.append("\t},")
    return out


lines = ["--!strict",
         "-- GENERATED by docs/miasto/tools (plan.py + extras.py + export.py). Do not edit by hand: change the plan",
         "-- scripts and re-export, or edit carefully and keep tests/town.spec.luau green.",
         "-- Coordinates: map-relative studs, x east, z south (north = -z). rot: degrees, front = (-sin, -cos).",
         "-- Types: src/shared/Data/Town/Types.luau. Plan picture: docs/miasto/plan.png.",
         "",
         'local Types = require("./Types")',
         "",
         "local city: Types.City = {",
         "\tsize = 800,"]
lines += ["\twall = " + lua(pts2(P.WALL)) + ","]
lines += block("gates", [dict(id=g["id"], x=g["x"], z=g["z"], rot=g["rot"], out=list(g["out"]), portal=g["portal"],
                              target=g["target"], arrive=list(g["arrive"])) for g in P.GATES],
               "Gate towers on the wall line; the portal field fills the passage; arrive = landing point inside.")
lines += ["\tterrain = {",
          "\t\tinsideNoise = { amp = 0.8, scale = 45, seed = 3 },",
          "\t\toutside = { fade = 30, base = 1.5, amp = 5, scale = 70, seed = 7, riseFrom = 330, rise = 0.35 },",
          "\t\tmoat = " + lua(P.MOAT) + ",",
          "\t\triver = " + lua(dict(pts=pts2(P.RIVER["points"]), width=P.RIVER["width"], bank=P.RIVER["bank"],
                                    bed=P.RIVER["bed"], water=P.RIVER["water"])) + ","]
lines += ["\t\tplateaus = {"]
for pl in P.PLATEAUS:
    lines.append("\t\t\t" + lua(dict(id=pl["id"], y=pl["y"], blend=pl["blend"], edge=pl["edge"],
                                     poly=pts2(pl["poly"]))) + ",")
lines += ["\t\t},", "\t\tramps = {"]
for r in P.RAMPS:
    lines.append("\t\t\t" + lua(dict(id=r["id"], name=r["name"], w=r["w"], stairs=r.get("stairs", False),
                                     pts=[[x, z, y] for x, z, y in r["pts"]])) + ",")
lines += ["\t\t},", "\t},"]
lines += block("streets", [dict(id=s["id"], name=s["name"], kind=s["kind"], w=s["w"], pts=pts2(s["pts"]))
                           for s in P.STREETS], "kind: main = Cobblestone, lane = Ground, alley = Mud (terrain paint)")
lines += block("bridges", [dict(id=b["id"], kind=b["kind"], x=b["x"], z=b["z"], rot=b["rot"], len=b["len"], w=b["w"])
                           for b in P.BRIDGES])
lines += block("squares", [dict(id=s["id"], mat=s["mat"], poly=pts2(s["poly"])) for s in P.SQUARES])
lines += block("specials", [dict(id=s["id"], kind=s["kind"], x=s["x"], z=s["z"], w=s["w"], d=s["d"], rot=s["rot"])
                            for s in P.SPECIALS], "Hand-placed buildings. w = frontage (local X), d = depth (local Z).")
lines += block("stalls", [dict(id=s["id"], x=s["x"], z=s["z"], rot=s["rot"], color=s["color"], npc=s.get("npc"))
                          for s in P.STALLS])
lines += ["\t-- NPC spots: x, z, facing (deg, same convention as rot). Ground y comes from TownTerrain.heightAt.",
          "\tnpcs = {"]
for n, (x, z, f) in P.NPCS.items():
    at = P.NPC_AT.get(n)
    extra = f', at = "{at}"' if at else ""
    lines.append(f"\t\t{n} = {{ x = {num(x)}, z = {num(z)}, facing = {num(f)}{extra} }},")
lines += ["\t},"]
lines += [f"\tspawn = {{ x = {num(P.SPAWN[0])}, z = {num(P.SPAWN[1])}, facing = {num(P.SPAWN[2])} }},"]
a = P.ARENA
lines += ["\tarena = " + lua(dict(x=a["x"], z=a["z"], half=a["half"], stands=a["stands"], exit=list(a["exit"]),
                                  duel=[list(a["duel"][0]), list(a["duel"][1])])) + ","]
lines += ["\tselectCamera = " + lua(dict(eye=list(P.SELECT_CAMERA["eye"]), look=list(P.SELECT_CAMERA["look"]))) + ","]
lines += [f"\tfountain = {lua(list(P.FOUNTAIN))},", f"\twells = {lua([list(w) for w in P.WELLS])},"]
lines += ["\tcemetery = " + lua(pts2(list(P.CEMETERY.exterior.coords)[:-1])) + ","]
lines += block("districts", [dict(id=d["id"], style=d["style"], poly=pts2(d["poly"])) for d in P.DISTRICTS])
lines += block("lots", [dict(id=l["id"], kind=l["kind"], style=l["style"], x=l["x"], z=l["z"], w=l["w"], d=l["d"],
                             rot=l["rot"], floors=l["floors"], seed=l["seed"], arcade=l["arcade"] or None)
                        for l in P.LOTS], "Ordinary houses (TownGen). arcade = rynek arcade (podcienia) on the front.")
lines += block("retaining", [dict(id=w["id"], kind=w["kind"], a=[w["x1"], w["z1"]], b=[w["x2"], w["z2"]],
                                  top=w["top"], bottom=w["bottom"], parapet=w["parapet"]) for w in P.RETAINING],
               "Stone retaining walls (wall centre line a..b, thickness 2.5), cliffs under the castle, ramp side walls.")
lines += block("gardens", [dict(id=g["id"], kind=g["kind"], seed=g["seed"], poly=g["poly"]) for g in E.GARDENS],
               "Every empty block is a garden/yard (no bare grass). kind decides the fill (MIASTO.md §7).")
lines += block("lamps", [dict(id=l["id"], kind=l["kind"], x=l["x"], z=l["z"]) for l in E.LAMPS])
lines += ["\toutside = {", f"\t\tforestStart = {E.FOREST_START},",
          "\t\twindmill = " + lua(E.WINDMILL) + ",",
          "\t\tfarms = " + lua(E.FARMS) + ",",
          "\t\truin = " + lua(E.WATCHTOWER_RUIN) + ","]
lines += ["\t\troads = {"]
for r in E.ROADS_OUT:
    lines.append("\t\t\t" + lua(dict(gate=r["gate"], w=r["w"], pts=pts2(r["pts"]), bridge=r["bridge"])) + ",")
lines += ["\t\t},", "\t\tfields = {"]
for f in E.FIELDS:
    lines.append("\t\t\t" + lua(dict(id=f["id"], crop=f["crop"], rows=f["rows"], seed=f["seed"], poly=f["poly"])) + ",")
lines += ["\t\t},", "\t},", "}", "", "return city", ""]
import os
ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."))
out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "shared", "Data", "Town", "city.luau")
heights = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, "tests", "fixtures", "cityHeights.luau")
os.makedirs(os.path.dirname(out), exist_ok=True)
open(out, "w").write("\n".join(lines))
print("wrote", out, len(lines), "lines", sum(len(l) for l in lines), "chars")

# Test vectors for TownTerrain.heightAt parity (Python reference vs Luau)
import random
r = random.Random(11)
vec = []
special = [(P.SPAWN[0], P.SPAWN[1])] + [(x, z) for x, z, _ in P.NPCS.values()] + [g["arrive"] for g in P.GATES]
for x, z in special:
    vec.append((x, z))
for _ in range(120):
    vec.append((round(r.uniform(-399, 399), 1), round(r.uniform(-399, 399), 1)))
for rr in P.RAMPS:
    for x, z, y in rr["pts"]:
        vec.append((x, z))
fx = ["--!strict", "-- GENERATED test vectors: { x, z, heightAt(x, z) } from the Python reference (docs/miasto/tools).",
      "return {"]
for x, z in vec:
    fx.append(f"\t{{ {num(x)}, {num(z)}, {P.height_at(x, z):.6f} }},")
fx += ["}", ""]
os.makedirs(os.path.dirname(heights) or ".", exist_ok=True)
open(heights, "w").write("\n".join(fx))
print("vectors", len(vec))
